###############
## 
####

GPU: [0,1,2,3]

VERBOSE: True

MODEL:
  MODE: 'NHHAZE'
  SESSION: 'ab_lamb_auto'

# Optimization arguments.
OPTIM:
  BATCH_SIZE: 2
  NUM_EPOCHS: 3000
  # NEPOCH_DECAY: [10]
  LR_INITIAL: 1e-4
  LR_MIN: 1e-6
  # BETA1: 0.9

TRAINING:
  VAL_AFTER_EVERY: 4
  RESUME: False
  TRAIN_PS: 128

  TRAIN_DIR: '/home/ps/nr/Curve/pairdata' # path to training data
  VAL_DIR: '/home/ps/nr/Curve/pairdata'    # path to validation data
  SAVE_DIR: './pretrained_model1'     # path to save models and images
  # SAVE_IMAGES: False
  DISPLAY_ID: 1
  BACKWARD_TYPE: 'fused'
  TRAIN: True

TESTING:
  #SOTS\HazeRD\LIVE\NTIRE\REALWORLD\ITS\fog
  DATAS: 'nhhaze'
